### ISSUE TITLE
libplacebo: vulkan registry vk.xml not found

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1680]
```
[6/42] Generating vulkan boilerplate with a custom command
FAILED: src/utils_gen.c 
"E:/MABS/msys64/mingw32/bin/python3.EXE" "../src/vulkan/utils_gen.py" "/usr/share/vulkan/registry/vk.xml" "src/utils_gen.c"
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 94, in <module>
    registry = ET.parse(xmlfile)
  File "E:/MABS/msys64/mingw32/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "E:/MABS/msys64/mingw32/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/vulkan/registry/vk.xml'
```

Might be an MSYS2 specific lack?

**Comment by 1480c1** [comment]
```
pacman -Fy /mingw64/share/vulkan/registry/vk.xml
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
mingw64/share/vulkan/registry/vk.xml is owned by mingw64/mingw-w64-x86_64-vulkan-headers 1.2.139-1
```
seems we might need to modify it to not hardcode that `/usr` path

**Comment by 1480c1** [comment]
`-Dvulkan-registry=$MINGW_PREFIX/share/vulkan/registry/vk.xml`

**Comment by LigH-de** [comment]
Wrong prefix.

Mine are in local[32|64]/share/vulkan/registry but

```
FileNotFoundError: [Errno 2] No such file or directory: 'E:/MABS/msys64/mingw32/share/vulkan/registry/vk.xml'
```

**Comment by 1480c1** [comment]
Done
