### ISSUE TITLE
Shaderc : "UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 9461: character maps to <undefined>"

### ISSUE THREAD

**Issue by pat357** [m-ab-s/media-autobuild_suite#1687]
Building Shaderc fails with the error in title.

[logs.zip](https://0x0.st/ifJ9.zip)
```
18:39:23 ┌ vulkan-loader git  ........................... [Updates found]
18:39:23 ├ Running uninstall...
18:39:24 ├ Running dependencies...
18:39:29 ├ Installing Vulkan-Headers...
18:39:29 ├ Running uninstall...
18:39:29 ├ Running cmake...
18:39:29 ├ Running build...
18:39:29 ├ Running install...
18:39:31 ├ Building Vulkan-Loader...
18:39:31 ├ Running cmake...
18:39:34 ├ Running build...
18:39:37 ├ Running install...
18:39:38 ├ Stripping...
18:39:38 └ vulkan-loader-git  ................................. [Updated]
18:39:38   Running git update for shaderc...
18:39:41 ┌ shaderc git  ................................. [Updates found]
18:39:41 ├ Running uninstall...
18:39:41 ├ Running glslang-clone...
18:39:46 ├ Running spirv-tools-clone...
18:39:50 ├ Running spirv-headers-clone...
18:39:51 ├ Running spirv-cross-clone...
18:39:57 ├ Running cmake...
18:40:02 ├ Running make...
Likely error (tail of the failed operation logfile):
cmd.exe /C "cd /D H:\Mingw645\build\shaderc-git\build-32bit\third_party\spirv-tools\source && H:\Mingw645\msys64\mingw32\bin\python3.exe H:/Mingw645/build/shaderc-git/third_party/spirv-tools/utils/generate_registry_tables.py --xml=H:/Mingw645/build/shaderc-git/third_party/spirv-headers/include/spirv/spir-v.xml --generator-output=H:/Mingw645/build/shaderc-git/build-32bit/third_party/spirv-tools/generators.inc"
Traceback (most recent call last):
  File "H:/Mingw645/build/shaderc-git/third_party/spirv-tools/utils/generate_registry_tables.py", line 90, in <module>
    main()
  File "H:/Mingw645/build/shaderc-git/third_party/spirv-tools/utils/generate_registry_tables.py", line 82, in main
    registry = xml.etree.ElementTree.fromstring(xml_in.read())
  File "H:/Mingw645/msys64/mingw32/lib/python3.8/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 9461: character maps to <undefined>
ninja: build stopped: subcommand failed.
make failed. Check H:/Mingw645/build/shaderc-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
All relevant logs have been anonymously uploaded to https://0x0.st/ifJ9.zip

**Comment by pat357** [comment]
I'll  close this issue : after the latest update from gcc and winpthreads, I no  longer get any error !
Also the sources from shader-c were updated, so it's difficult now what the culprit was.
