### ISSUE TITLE
[mingw64] [repo] mpv fails to build due to parallel processing problems

### ISSUE THREAD

**Issue by jet082** [m-ab-s/media-autobuild_suite#1760]
Whenever I attempt to build mpv with the suite, it fails at variable parts of the configure step. Sometimes it even succeeds configuring, but it typically fails - always in different places, with the below error.

Now, this can be fixed by editing ``/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py`` and changing the line ``shutil.rmtree(dir)`` to ``shutil.rmtree(dir, ignore_errors=True)``. I have confirmed after that it builds and runs just fine.

``` bash
$ LDFLAGS="-pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib -Wl,--image-base,0x140000000,--high-entropy-va -LC:/PROGRA~1/NVIDIA~2/CUDA/v10.2/lib/x64 -lgomp"
$ CXXFLAGS="-mthreads -mtune=generic -O2 -pipe"
$ CFLAGS="-mthreads -mtune=generic -O2 -pipe -IC:/PROGRA~1/NVIDIA~2/CUDA/v10.2/include -fopenmp" 
$ CPPFLAGS="-D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1"
$ /usr/bin/python waf configure --prefix=/local64 --bindir=/local64/bin-video --disable-debug-build --lua=luajit --enable-dvdnav --enable-cdda --enable-libmpv-shared --enable-openal --enable-sdl2 --enable-static-build


Setting top to                           : /trunk/build/mpv-git
Setting out to                           : /trunk/build/mpv-git/build
Checking for waf version in 1.8.4-2.1.0  : ok
Checking for program 'cc'                : ['ccache', 'gcc']
Checking for program 'pkg-config'        : ['/mingw64/bin/pkg-config', '--static']
Checking for program 'ar'                : /mingw64/bin/ar
Checking for program 'rst2html'          : /mingw64/bin/rst2html
Checking for program 'rst2man'           : /mingw64/bin/rst2man
Checking for program 'rst2pdf'           : not found
Checking for program 'windres'           : /mingw64/bin/windres
Checking for program 'perl'              : /mingw64/bin/perl
Checking for 'clang' (C compiler)        : not found
Checking for 'gcc' (C compiler)          : ccache gcc
Detected target OS:                      : os-win32
Checking for compiler flags -std=c11     : yes
Checking for compiler flags -Werror -Werror=implicit-function-declaration : yes
Checking for compiler flags -Werror -Wno-error=deprecated-declarations    : yes
Checking for compiler flags -Werror -Wno-error=unused-function            : yes
Checking for compiler flags -Werror -Wempty-body                          : yes
Checking for compiler flags -Werror -Wdisabled-optimization               : Traceback (most recent call last):
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 118, in waf_entry_point
    run_commands()
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 178, in run_commands
    ctx=run_command(cmd_name)
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Scripting.py", line 169, in run_command
    ctx.execute()
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/trunk/build/mpv-git/wscript", line 934, in configure
    ctx.load('detections.compiler')
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 155, in load
    func(self)
  File "/trunk/build/mpv-git/waftools/detections/compiler.py", line 91, in configure
    __add_generic_flags__(ctx)
  File "/trunk/build/mpv-git/waftools/detections/compiler.py", line 34, in __add_generic_flags__
    __test_and_add_flags__(ctx, ["-Werror=implicit-function-declaration",
  File "/trunk/build/mpv-git/waftools/detections/compiler.py", line 16, in __test_and_add_flags__
    if ctx.check_cc(cflags='-Werror ' + flag, mandatory=False):
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 174, in fun
    return f(*k,**kw)
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Tools/c_config.py", line 431, in check_cc
    return self.check(*k,**kw)
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 174, in fun
    return f(*k,**kw)
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Tools/c_config.py", line 387, in check
    ret=self.run_build(*k,**kw)
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 174, in fun
    return f(*k,**kw)
  File "/trunk/build/mpv-git/.waf3-2.0.9-10a533182bd85c3f45a157fb5d62db50/waflib/Configure.py", line 336, in run_build
    shutil.rmtree(dir)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 90] Directory not empty: 'testbuild'
```

**Comment by 1480c1** [comment]
we do not control the waf nor can reliably modify how waf works.

you might need to report that to mpv or alternatively waf depending on how they respond

**Comment by 1480c1** [comment]
Since nothing can be really done by us, I will close this issue, if you think it's an important enough issue, you can comment on it
