### ISSUE TITLE
mingw32 harfbuzz: meson build error

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1841]
[logs.zip](https://0x0.st/iduI.zip)

From ab-suite.meson.log:
```
Traceback (most recent call last):
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/msetup.py", line 253, in run
    app.generate()
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/msetup.py", line 161, in generate
    self._generate(env)
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/msetup.py", line 200, in _generate
    intr.run()
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/interpreter.py", line 4703, in run
    super().run()

...

  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/compilers/mixins/clike.py", line 1072, in output_is_64bit
    return self.sizeof('void *', '', env) == 8
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/compilers/mixins/clike.py", line 610, in sizeof
    res = self.run(t.format(**fargs), env, extra_args=extra_args,
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/compilers/mixins/clike.py", line 486, in run
    return compilers.RunResult(False)
  File "E:/MABS/msys64/mingw32/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/compilers/compilers.py", line 1181, in _build_wrapper
    yield r
  File "E:/MABS/msys64/mingw32/lib/python3.8/contextlib.py", line 124, in __exit__
    raise RuntimeError("generator didn't stop")
```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5474220/logs.zip)

**Comment by LigH-de** [comment]
Compilation passed on a different PC.

**Comment by LigH-de** [comment]
Reinstallation of the whole suite. Issue persists on a Win7 PC. Could there be anything Win10 specific in meson now?!

**Comment by 1480c1** [comment]
can you try opening up mintty on your win7 machine and run
```bash
source /local32/etc/profile2.local
source /build/media-suite_helper.sh
do_vcs "https://code.videolan.org/videolan/dav1d.git"
do_mesoninstall video -Denable_{tests,examples}=false
```
and show the output?

**Comment by LigH-de** [comment]
As requested - it built with some "fatal" error messages regarding a `.ninja_log` file, but eventually successfully.

[dav1d-test.txt](https://github.com/m-ab-s/media-autobuild_suite/files/5492919/dav1d-test.txt)

**Comment by 1480c1** [comment]
Was wanting to check if the issue was meson related or not

**Comment by LigH-de** [comment]
MSYS2 updated meson to 0.56; harfbuzz builds.
