### ISSUE TITLE
harfbuzz: meson fails (temporary file handling)

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1934]
Seems to be an issue with the handling of the temporary build directory. First it is not empty (so the previous output.exe was probably not deleted in time, kept by a monitoring Windows process), then access to the output.exe is denied when building new configure test applications. But after the meson script aborts, the temporary directory is then empty...

```
...
Traceback (most recent call last):
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1570, in cleanup
    super().cleanup()
  File "E:/MABS/msys64/mingw32/lib/python3.8/tempfile.py", line 831, in cleanup
    self._rmtree(self.name)
  File "E:/MABS/msys64/mingw32/lib/python3.8/tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "E:/MABS/msys64/mingw32/lib/python3.8/shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:/MABS/msys64/mingw32/lib/python3.8/shutil.py", line 622, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "E:/MABS/msys64/mingw32/lib/python3.8/shutil.py", line 620, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] {{Directory not empty}}: 'E:/MABS/build/harfbuzz-git/build-32bit/meson-private/tmpp1a_c1s1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1564, in __exit__
    super().__exit__(exc, value, tb)
  File "E:/MABS/msys64/mingw32/lib/python3.8/tempfile.py", line 827, in __exit__
    self.cleanup()
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1572, in cleanup
    windows_proof_rmtree(self.name)
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1527, in windows_proof_rmtree
    _make_tree_writable(f)
  File "E:/MABS/msys64/mingw32/lib/python3.8/site-packages/mesonbuild/mesonlib/universal.py", line 1517, in _make_tree_writable
    os.chmod(fpath, os.stat(fpath).st_mode | stat.S_IWRITE | stat.S_IREAD)
PermissionError: [WinError 5] {{Access denied}}: 'E:/MABS/build/harfbuzz-git/build-32bit/meson-private/tmpp1a_c1s1/output.exe'
...
```

I believe there was already a bug report to meson for MSYS2 with a similar issue. — That was reported in [harfbuzz issue 2738](https://github.com/harfbuzz/harfbuzz/issues/2738).

[logs.zip](https://0x0.st/-K51.zip) — [logs.zip with additional meson subdirectories](https://github.com/m-ab-s/media-autobuild_suite/files/6067924/logs.zip)

[meson issue 8447](https://github.com/mesonbuild/meson/issues/8447)

**Comment by lazka** [comment]
Either `_make_tree_writable` needs to be dropped, or moved into the retry loop.

**Comment by LigH-de** [comment]
Doesn't look like the meson team cares, despite a suggested fix...

**Comment by LigH-de** [comment]
MSYS2 provided meson 0.57.1-2, appears fixed.

**Comment by wpapp** [comment]
meson fails

`22:47:01 ┌ harfbuzz git  ............................. [Recently updated]
22:47:03 ├ Running meson...
Likely error (tail of the failed operation logfile):
C++ linker for the host machine: g++.bat ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports link arguments -Bsymbolic-functions: YES
Compiler for C++ supports arguments -fno-exceptions: YES
Compiler for C++ supports arguments -fno-rtti: YES
Compiler for C++ supports arguments -fno-threadsafe-statics: YES
Compiler for C++ supports arguments -fvisibility-inlines-hidden: YES
Library m found: YES
Found pkg-config: --keep-system-libs (1.7.3)
meson failed. Check G:/FFmpeg/build/harfbuzz-git/build-64bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
22:47:07   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-cQD.zip
Copy and paste [logs.zip](https://0x0.st/-cQD.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.`

**Comment by 1480c1** [comment]
separate issue, open a new one
