### ISSUE TITLE
[clang] [mingw64] [libtiff] ModuleNotFoundError: No module named 'sphinx'... in my system's python

### ISSUE THREAD

**Issue by snowbie** [m-ab-s/media-autobuild_suite#2205]
``` bash
┌ libtiff git  ........................................ [Recently updated]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
FAILED: doc/html/index.html C:/mabs/build/libtiff-git/build-64bit/doc/html/index.html
cmd.exe /C "cd /D C:\mabs\build\libtiff-git\doc && C:\mabs\msys64\mingw64\bin\cmake.exe -E make_directory C:/mabs/build/libtiff-git/build-64bit/doc/cache && C:\mabs\msys64\mingw64\bin\cmake.exe -E make_directory C:/mabs/build/libtiff-git/build-64bit/doc/html && C:\Users\Snow\loc\sync\app\c\py39\python-3.9.10.amd64\Scripts\sphinx-build.exe -D release=4.4.0 -D version=4.4 -d C:/mabs/build/libtiff-git/build-64bit/doc/cache -b html C:/mabs/build/libtiff-git/doc C:/mabs/build/libtiff-git/build-64bit/doc/html"
Traceback (most recent call last):
  File "C:/mabs/msys64/mingw64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/mabs/msys64/mingw64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/Users/Snow/loc/sync/app/c/py39/python-3.9.10.amd64/Scripts/sphinx-build.exe/__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'sphinx'
ninja: build stopped: subcommand failed.
build failed. Check C:/mabs/build/libtiff-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

```

[logs.zip](https://0x0.st/oMQA.zip)

**Comment by 1480c1** [comment]
`C:\Users\Snow\loc\sync\app\c\py39\python-3.9.10.amd64\Scripts\sphinx-build.exe`

seems outside scripts are leaking, other than suggesting to remove this path while building, not sure what I can do to fix this atm

**Comment by snowbie** [comment]
> `C:\Users\Snow\loc\sync\app\c\py39\python-3.9.10.amd64\Scripts\sphinx-build.exe`
> 
> seems outside scripts are leaking, other than suggesting to remove this path while building, not sure what I can do to fix this atm

Worked. Still strange how that managed to happen. I've never had the suite leak before. What I have had happen numerous times was libtiff failing to build then eventually sorting itself out within a few days, but this time I wasn't so sure.
