### ISSUE TITLE
ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.

### ISSUE THREAD

**Issue by cs2003sun** [m-ab-s/media-autobuild_suite#2559]
It occurs in several packages. Not only in "jo" but also in "fontconfig-git",  "harfbuzz-git" and etc. 

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/13538398/logs.zip)

```
 Running git update for jo...
┌ jo git  ............................................. [Recently updated]
├ Running meson...
Likely error (tail of the failed operation logfile):
  User defined options
    backend        : ninja
    bindir         : bin-global
    buildtype      : release
    default_library: static
    prefix         : C:/ffmpeg/local64

Found ninja-1.11.1 at C:\ffmpeg\msys64\mingw64\bin/ninja.EXE

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
meson failed. Check C:/ffmpeg/build/jo-git/build-64bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

Attach C:\ffmpeg\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

```

**Comment by 1480c1** [comment]
In your log, I see
```py
Traceback (most recent call last):
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/msetup.py", line 358, in run
    app.generate()
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/msetup.py", line 181, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/msetup.py", line 251, in _generate
    captured_compile_args = intr.backend.generate(capture, vslite_ctx)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 632, in generate
    self.generate_target(t)
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 1057, in generate_target
    elem = self.generate_link(target, outname, final_obj_list, linker, pch_objects, stdlib_args=stdlib_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 3474, in generate_link
    dep_targets.extend(self.guess_external_link_dependencies(linker, target, commands, internal))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/backend/ninjabackend.py", line 3313, in guess_external_link_dependencies
    search_dirs = tuple(search_dirs) + tuple(linker.get_library_dirs(self.environment))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/compilers/mixins/clike.py", line 260, in get_library_dirs
    return self._get_library_dirs(env, elf_class).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/compilers/mixins/clike.py", line 219, in _get_library_dirs
    dirs = self.get_compiler_dirs(env, 'libraries')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/compilers/mixins/gnu.py", line 513, in get_compiler_dirs
    return self._split_fetch_real_dirs(line.split('=', 1)[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/site-packages/mesonbuild/compilers/mixins/gnu.py", line 495, in _split_fetch_real_dirs
    if pobj.exists():
       ^^^^^^^^^^^^^
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/pathlib.py", line 1237, in exists
    self.stat()
  File "C:/ffmpeg/msys64/mingw64/lib/python3.11/pathlib.py", line 1015, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -2144272384]        ̺   BitLocker     ̺    ȣȭ        ֽ  ϴ .      ǿ           ̺               ؾ   մϴ : 'D:/a/msys64/mingw64/lib/x86_64-w64-mingw32/13.2.0'
The Meson build system
Version: 1.3.0
```

Based on the error, I think you may have some kind of issue with bitlocker?

**Comment by 1480c1** [comment]
I doubt I would be able to reproduce, if you encounter the issue again, you can comment, and I can reopen and see if I can find a way
